### ISSUE TITLE
Unit tests broken on HEAD due to file processor contract change

### ISSUE THREAD

**Issue by mglaman** [rectorphp/rector-nette#21]
HEAD is failing, and so are any tests in packages relying on the AbstractRectorTestCase class from Rector

https://github.com/rectorphp/rector-nette/commit/0227bb6f43bde75467ee2c14219713784db47afa

```
        $file = new File($fileInfo, $fileInfo->getContents());
        $this->applicationFileProcessor->run([$file], $configuration);
```

**Comment by TomasVotruba** [comment]
Waits on https://github.com/rectorphp/rector-src/pull/362

**Comment by TomasVotruba** [comment]
Already resolved in https://github.com/rectorphp/rector-src/pull/362
